Feature/animations
aaccent/vpo-ex-pro_layout pull request #76
Opened 2024-07-11 14:29 UTC by regina-ms

2024-07-11 14:30 UTC, regina-ms commented
- #69 
- #70 
- #71

2024-07-15 07:31 UTC, foxhable approved these changes

2024-07-15 07:42 UTC, foxhable requested changes

2024-07-15 07:42 UTC, foxhable commented on src/features/animation/scroll.js
> +                    markers: true,
Не убрала маркеры

2024-07-15 07:42 UTC, foxhable commented on src/features/animation/scroll.js
> +                        trigger: '.content__text',
На странице картинок может быть несколько. Такой тригер значит что для всех картинок тригером будет первый на странице `.content__text`. Нужно сделать тригером саму картинку, чтобы анимации были индивидуальны

2024-07-15 07:42 UTC, foxhable commented on src/features/animation/scroll.js
> +                        pin: false,
`pin: false` и так по умолчанию

2024-07-15 08:01 UTC, foxhable approved these changes

2024-07-15 08:01 UTC, merged